name: 'Glados-Checkin Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - cookie: COOKIE
            dingtalk_token: DINGTALK_TOKEN
    steps:
      - name: Working
        with:
          cookie: ${{ secrets[matrix.cookie] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
        run: 
          cd ${{ github.action_path }}
          pip install -r ./requirements.txt
          python3 ./main.py
        shell: bash