name: 'Glados-Checkin Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - cookie: COOKIE
            dingtalk_token: DINGTALK_TOKEN
    steps:
      - name: Working
        env:
          COOKIE: ${{ secrets[matrix.cookie] }}
          DINGTALK_TOKEN: ${{ secrets[matrix.dingtalk_token] }}
        run: |
          cd ${{ github.workspace }}
          pip install -r ./requirements.txt
          python3 ./main.py
        shell: bash